/*
Zde se vyplnují položky menu

Je potřeba vytvořit záznam v dané skupině pro všechny stránky v pořadím v jakém je chceme mít
 */
const menu = {
    '/': [
        {
            title: 'Příručka hráče',
            collapsable: true,
            children: [
                '/prirucka-hrace/predmluva',
                '/prirucka-hrace/uvod',
                '/prirucka-hrace/1-kapitola',
                '/prirucka-hrace/2-kapitola',
                '/prirucka-hrace/3-kapitola',
                '/prirucka-hrace/4-kapitola',
                '/prirucka-hrace/5-kapitola',
                '/prirucka-hrace/6-kapitola',
                '/prirucka-hrace/7-kapitola',
                '/prirucka-hrace/8-kapitola',
                '/prirucka-hrace/9-kapitola',
                '/prirucka-hrace/10-kapitola',
                '/prirucka-hrace/11-kapitola',
                '/prirucka-hrace/dodatek-a',
                '/prirucka-hrace/dodatek-b',
                '/prirucka-hrace/dodatek-c',
                '/prirucka-hrace/dodatek-d',
                '/prirucka-hrace/dodatek-e',
            ]
        },{
            title: 'Průvodce pána jeskyně',
            collapsable: true,
            children: [
                '/pruvodce-pana-jeskyne/uvod',
                '/pruvodce-pana-jeskyne/1-kapitola',
                '/pruvodce-pana-jeskyne/2-kapitola',
                '/pruvodce-pana-jeskyne/3-kapitola',
                '/pruvodce-pana-jeskyne/4-kapitola',
                '/pruvodce-pana-jeskyne/5-kapitola',
                '/pruvodce-pana-jeskyne/6-kapitola',
                '/pruvodce-pana-jeskyne/7-kapitola',
                '/pruvodce-pana-jeskyne/8-kapitola',
                '/pruvodce-pana-jeskyne/9-kapitola',
                '/pruvodce-pana-jeskyne/dodatek-A',
                '/pruvodce-pana-jeskyne/dodatek-B',
                '/pruvodce-pana-jeskyne/dodatek-C',
                '/pruvodce-pana-jeskyne/dodatek-D',
            ]
        },{
            title: 'Bestiář',
            collapsable: true,
            children: [
                'bestiar/uvod',
                'bestiar/abolet',
                'bestiar/andele',
                'bestiar/ankheg',
                'bestiar/arakokra',
                'bestiar/azer',
                'bestiar/bazilisek',
                'bestiar/behir',
                'bestiar/blekotajici-tlamac',
                'bestiar/bludicka',
                'bestiar/bulta',
                'bestiar/chimera',
                'bestiar/chrlic',
                'bestiar/chuul',
                'bestiar/dablove',
                'bestiar/demoni',
                'bestiar/diblik',
                'bestiar/dinosauri',
                'bestiar/divous',
                'bestiar/draci-zelva',
                'bestiar/draci',
                'bestiar/drak-stinovy',
                'bestiar/drakostej',
                'bestiar/dravouk',
                'bestiar/dryada',
                'bestiar/duch',
                'bestiar/duergar',
                'bestiar/dvojnik',
                'bestiar/elementalove',
                'bestiar/elfove-drowove',
                'bestiar/empyrean',
                'bestiar/ent',
                'bestiar/etin',
                'bestiar/fext',
                'bestiar/flamp',
                'bestiar/fomorian',
                'bestiar/galeb-dur',
                'bestiar/geniove',
                'bestiar/ghulove',
                'bestiar/githove',
                'bestiar/gnolove',
                'bestiar/gnom-hlubinny',
                'bestiar/goblini',
                'bestiar/gobri',
                'bestiar/golemove',
                'bestiar/gorgon',
                'bestiar/grel',
                'bestiar/gryf',
                'bestiar/gryk',
                'bestiar/hakovec',
                'bestiar/harpyje',
                'bestiar/hipogryf',
                'bestiar/homunkulus',
                'bestiar/houby',
                'bestiar/hrotoun',
                'bestiar/hydra',
                'bestiar/jednorozec',
                'bestiar/jesterci',
                'bestiar/jezibaby',
                'bestiar/kambion',
                'bestiar/kenku',
                'bestiar/kentaur',
                'bestiar/klamopard',
                'bestiar/klepetnatec',
                'bestiar/koboldi',
                'bestiar/kokatrice',
                'bestiar/kostej',
                'bestiar/kostlivci',
                'bestiar/kovatl',
                'bestiar/kraken',
                'bestiar/krapnitec',
                'bestiar/kuo-toove',
                'bestiar/kyklop',
                'bestiar/lamie',
                'bestiar/litice',
                'bestiar/lykantropove',
                'bestiar/magmar',
                'bestiar/mantikora',
                'bestiar/meduza',
                'bestiar/mefiti',
                'bestiar/mimik',
                'bestiar/minotaurus',
                'bestiar/modroni',
                'bestiar/moran',
                'bestiar/morian',
                'bestiar/mozkozrout',
                'bestiar/mrchodravec',
                'bestiar/mstitel',
                'bestiar/mumie',
                'bestiar/mykonidi',
                'bestiar/nagy',
                'bestiar/neviditelny-stopar',
                'bestiar/nocni-mura',
                'bestiar/noh',
                'bestiar/notik',
                'bestiar/obri',
                'bestiar/obrneny-des',
                'bestiar/ohniva-lebka',
                'bestiar/on',
                'bestiar/orkove',
                'bestiar/otyugh',
                'bestiar/ozivle-predmety',
                'bestiar/pavoucnatec',
                'bestiar/pegas',
                'bestiar/pekelny-ohar',
                'bestiar/peryton',
                'bestiar/plastnik',
                'bestiar/plazivy-parat',
                'bestiar/poletucha',
                'bestiar/polodrak',
                'bestiar/polokostej',
                'bestiar/prizrak',
                'bestiar/pseudodrak',
                'bestiar/purpurovy-cerv',
                'bestiar/quagot',
                'bestiar/raksaza',
                'bestiar/remorazove',
                'bestiar/ropusak',
                'bestiar/rozumhlt',
                'bestiar/rytir-smrti',
                'bestiar/rzivy-netvor',
                'bestiar/sahuagini',
                'bestiar/sakalodlak',
                'bestiar/salamandri',
                'bestiar/satyr',
                'bestiar/sfingy',
                'bestiar/skuruti',
                'bestiar/sladi',
                'bestiar/slizy',
                'bestiar/sneti',
                'bestiar/sovodved',
                'bestiar/spektra',
                'bestiar/stin',
                'bestiar/stitovy-strazce',
                'bestiar/strasak',
                'bestiar/striga',
                'bestiar/sukuba-nebo-inkubus',
                'bestiar/tarask',
                'bestiar/temnoplast',
                'bestiar/thri-kreen',
                'bestiar/tlejici-valivec',
                'bestiar/troglodyt',
                'bestiar/troll',
                'bestiar/upiri',
                'bestiar/vili-dracek',
                'bestiar/vodni-div',
                'bestiar/vyverna',
                'bestiar/xorn',
                'bestiar/yettiove',
                'bestiar/yuan-tiove',
                'bestiar/yugoloti',
                'bestiar/zlobri',
                'bestiar/zombie',
                'bestiar/zrici',
            ]
        },{
            title: 'Grimoar',
            collapsable: true,
            children: [
                '/grimoar/grimoar-jmen',
                '/grimoar/grimoar-moci',
            ]
        },{
            title: 'Soupis povolání',
            collapsable: true,
            children: [
                '/soupis/carodej',
            ]
        },
    ]
};


module.exports = menu;